spring:
  main:
    web-application-type: none
  datasource:
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 300000

batch:
  google-api-key: ${GOOGLE_API_KEY:}
  kakao-rest-api-key: ${KAKAO_REST_API_KEY:}
